### ISSUE TITLE
transmissionrpc: Unhandled python exception in read callback: AttributeError: No attribute key

### ISSUE THREAD

**Issue by jerryjacobs** [akosiaris/collectd_transmission#1]
I tried to install using pip and the plugin will login to transmission, when I set the incorrect username I get a 401 unauthorized inside collectd log. When everything is configured correct then I get this error:

[2015-05-14 09:19:34] Unhandled python exception in read callback: AttributeError: No attribute key
[2015-05-14 09:19:34] Traceback (most recent call last):
[2015-05-14 09:19:34]   File "/usr/lib/python2.7/site-packages/collectd_transmission/__init__.py", line 135, in get_stats
    vl.dispatch(values=[field_getter(stats, metric, category)])
[2015-05-14 09:19:34]   File "/usr/lib/python2.7/site-packages/collectd_transmission/__init__.py", line 110, in field_getter
    return stats.key
[2015-05-14 09:19:34]   File "/usr/lib/python2.7/site-packages/transmissionrpc/session.py", line 29, in __getattr__
    raise AttributeError('No attribute %s' % name)

System: Arch Linux kernel 3.14.38-1-lts
Python: 2.7.9
Collectd: 5.4.2.git
Transmission: 2.84
Python transmissionrpc: 0.11

Hope you can reproduce this,
Kind regards
Jerry

**Comment by akosiaris** [comment]
Hello, yes I can reproduce this on a Debian Jessie box with default packages installed. Versions are about the same as yours (collectd is 5.4.1 but it is obviously unrelated). Seems like the problem is about torrentCount (one of the most useful stats). I 'll post an update shortly

**Comment by jerryjacobs** [comment]
Thanks!

**Comment by akosiaris** [comment]
Yes, working on it already, got sidetracked by fixing a couple of other things on the way

**Comment by akosiaris** [comment]
https://pypi.python.org/pypi/collectd_transmission/v2.2
Done. Thanks for reporting this.

**Comment by jerryjacobs** [comment]
No problem, there only seemed to be a few Collectd Transmission RPC plugins and yours is the most extensive. It generates graphs but the collectd/rrd frontend I currently use crashes on the collectd plugin scripts output. I use https://github.com/facette/facette which is a very nice and easy to deploy and configure collectd frontend which has zero dependencies because it is written on GoLang. 

Thanks for fixing!
