### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by Lokotito** [akosiaris/collectd_transmission#14]
I installed as guide and add this lines in my collecd.conf:

```
<Plugin python>
#    ModulePath "/path/to/module/dir" # Not needed if installed via pip or package
    LogTraces false
    Interactive false
    Import "collectd_transmission"
    <Module collectd_transmission>
        username "MyUser" # Required
        password "MyPass" # Required
        address "http://my-local.ip:9091/transmission/rpc" # Optional, defaults to "http://localhost:9091/transmission/rpc"
        timeout "5" # Optional, defaults to 5
    </Module>
</Plugin>
```

but when restart the collect service have this error:

> python plugin: Error importing module "collectd_transmission".
> Unhandled python exception in importing module: ImportError: No module named collectd_transmission

collectb 5.4.1-6, phyton 3.4, python-transmissionrpc 0.11-1, debian jessie (3.16.0-4-amd64)

**Comment by Lokotito** [comment]
My bad,
Must to specify my ModulePath (example /usr/lib/python2.7/dist-packages/).
Even if I installed via pip.

Best regards.

**Comment by akosiaris** [comment]
Hm, that should not be required. In fact I just tried to reproduce and failed. My test was just spin up a jessie VM, install pip and collectd via apt and `sudo pip install collectd-transmission`. Then paste the sample config in collectd.conf specifying username/password and removing address.

The standard locations `/usr/local/lib/python2.7/dist-packages` and `/usr/lib/python2.7/dist-packages` should anyway be in collectd's python plugin path. I 've actually tested that on Debian jessie as well as precise, trusty, stretch and xenial. 

I am also slightly perplexed by pip installing in `/usr/lib/python2.7/dist-packages`. My guess is you have a typo there and it's `/usr/**local**/lib/python2.7/dist-packages` ? Or did you somehow force pip to install in /usr/lib ? Not that it matters much, both paths should be honoured by the plugin.

Anyway, I 'll close this. Feel free to reopen if you have more info to provide like a concrete reproduction of the behavior. Thanks!

**Comment by Lokotito** [comment]
Thank you for your answer, will check my pip configs for future.

Best regards.
